# Generated by Django 3.2.7 on 2021-10-01 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orderupdate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='subcategory',
            new_name='brand',
        ),
    ]
